//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class GarageDBEntities : DbContext
{
    public GarageDBEntities()
        : base("name=GarageDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Booking> Bookings { get; set; }
    public virtual DbSet<BookingLink> BookingLinks { get; set; }
    public virtual DbSet<Cart> Carts { get; set; }
    public virtual DbSet<ClientInfo> ClientInfoes { get; set; }
    public virtual DbSet<Furniture> Furnitures { get; set; }
    public virtual DbSet<Hostel> Hostels { get; set; }
    public virtual DbSet<Hosteler> Hostelers { get; set; }
    public virtual DbSet<Product> Products { get; set; }
    public virtual DbSet<ProductType> ProductTypes { get; set; }
    public virtual DbSet<RoomPrice> RoomPrices { get; set; }
    public virtual DbSet<UserInformation> UserInformations { get; set; }
    public virtual DbSet<Visit> Visits { get; set; }
    public virtual DbSet<Comment> Comments { get; set; }
}
